function b = myrhsstuffDAE(d1,d2,d3,d4,g,l1,l2,l3,l4,m1,m2,m3,m4,th1,th2,th3,th4,th1d,th2d,th3d,th4d)
%MYRHSSTUFFDAE
%    B = MYRHSSTUFFDAE(D1,D2,D3,D4,G,L1,L2,L3,L4,M1,M2,M3,M4,TH1,TH2,TH3,TH4,TH1D,TH2D,TH3D,TH4D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Nov-2018 19:30:45

t2 = th1d.^2;
t3 = sin(th1);
t4 = cos(th1);
t5 = th2d.^2;
t6 = sin(th2);
t7 = cos(th2);
t8 = th3d.^2;
t9 = sin(th3);
t10 = cos(th3);
t11 = th4d.^2;
t12 = sin(th4);
t13 = cos(th4);
b = [0.0;g.*m1;0.0;g.*m2;0.0;g.*m3;0.0;g.*m4;0.0;0.0;0.0;0.0;-d1.*t2.*t3;d1.*t2.*t4;t2.*(d1.*t3-l1.*t3)-d2.*t5.*t6;-t2.*(d1.*t4-l1.*t4)+d2.*t5.*t7;t5.*(d2.*t6-l2.*t6)-d3.*t8.*t9;-t5.*(d2.*t7-l2.*t7)+d3.*t8.*t10;t8.*(d3.*t9-l3.*t9)-d4.*t11.*t12;-t8.*(d3.*t10-l3.*t10)+d4.*t11.*t13;t11.*(d4.*t12-l4.*t12);-t11.*(d4.*t13-l4.*t13);0.0];
